[package]
name = "url-mapper-rs"
version = "0.1.0"
edition = "2018"
license-file = "LICENSE"
description = "learning rust"
homepage = "https://jasonkayzk.github.io/"
readme = "README.md"
repository = "https://github.com/JasonkayZK/rust-learn/"
authors = ["Jasonkay jasonkayzk@gmail.com"]

[dependencies]
anyhow = "1.0.41"
base64 = "0.13.0"
config = { version = "0.11.0", features = ["json"] }
lazy_static = "1.4.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.5", features = ["runtime-tokio-rustls", "postgres", "migrate"] }
tokio = { version = "1.6.2", features = ["full"] }
async-trait = { version = "0.1.51" }
hyper = "0.14.9"
routerify = "2.1.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
tera = "1.12.1"
