[package]
name = "ffi-demo"
version = "0.1.0"
edition = "2018"
license-file = "LICENSE"
description = "a demo for ffi"
homepage = "https://jasonkayzk.github.io/"
readme = "README.md"
repository = "https://github.com/JasonkayZK/rust-learn/"
authors = ["Jasonkay jasonkayzk@gmail.com"]

[dependencies]
libc = "0.2.0"
